"""Constants for Stock app."""

# CATEGORY

CATEGORY_NAME_LENGTH = 100
CATEGORY_SLUG_LENGTH = 50

# PRODUCT

PRODUCT_NAME_LENGTH = 100
PRODUCT_SLUG_LENGTH = 50
PRODUCT_PRICE_MAX_DIGITS = 10
PRODUCT_PRICE_DECIMAL_PLACES = 2

# TEXT_SLICE

TEXT_SLICE = 20
